// Compiles contracts/src/Sworn.sol with forge into demo/.forge-out (nothing is written under
// contracts/) and emits:
//   src/chain/sworn.abi.ts       — the ABI the UI decodes events and reads views with
//   test/fixtures/sworn.bytecode — creation bytecode, used only by the anvil test to deploy Sworn
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const demo = join(dirname(fileURLToPath(import.meta.url)), "..");
const contracts = join(demo, "..", "contracts");
const out = join(demo, ".forge-out");
const cache = join(demo, ".forge-cache");

execFileSync(
  "forge",
  ["build", "--root", contracts, "--out", out, "--cache-path", cache],
  { stdio: "inherit" },
);

const artifact = JSON.parse(readFileSync(join(out, "Sworn.sol", "Sworn.json"), "utf8"));
writeFileSync(
  join(demo, "src", "chain", "sworn.abi.ts"),
  `// GENERATED by scripts/gen-abi.mjs from contracts/src/Sworn.sol — do not edit.\n` +
    `export const swornAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
);
mkdirSync(join(demo, "test", "fixtures"), { recursive: true });
writeFileSync(join(demo, "test", "fixtures", "sworn.bytecode"), artifact.bytecode.object + "\n");
console.log(`sworn.abi.ts: ${artifact.abi.length} entries; bytecode ${artifact.bytecode.object.length / 2 - 1} bytes`);
