// GENERATED by scripts/gen-abi.mjs from contracts/src/Sworn.sol — do not edit.
export const swornAbi = [
  {
    "type": "function",
    "name": "ANSWER_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "BOND_TOKEN",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "CHAIN_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "CHALLENGE_PERIOD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DOMAIN_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "GUEST_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "GUEST_VKEY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_AGE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "QUESTION_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SP1_VERIFIER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SWORN_ANSWER_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "UNBOND_DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "beginUnbond",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "bond",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "challenge",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "q",
        "type": "tuple",
        "internalType": "struct Sworn.Question",
        "components": [
          {
            "name": "chainId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "blockNumber",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "blockHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "from",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "feeToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "gasLimit",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "a",
        "type": "tuple",
        "internalType": "struct Sworn.Answer",
        "components": [
          {
            "name": "success",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "returnDataHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "gasUsed",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "feeCharged",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receiverBefore",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "receiverAfter",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "publicValues",
        "type": "bytes",
        "internalType": "bytes"
      },
      {
        "name": "proof",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "digestOf",
    "inputs": [
      {
        "name": "q",
        "type": "tuple",
        "internalType": "struct Sworn.Question",
        "components": [
          {
            "name": "chainId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "blockNumber",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "blockHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "from",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "feeToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "gasLimit",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "a",
        "type": "tuple",
        "internalType": "struct Sworn.Answer",
        "components": [
          {
            "name": "success",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "returnDataHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "gasUsed",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "feeCharged",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receiverBefore",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "receiverAfter",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "domainSeparator",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "hashAnswer",
    "inputs": [
      {
        "name": "a",
        "type": "tuple",
        "internalType": "struct Sworn.Answer",
        "components": [
          {
            "name": "success",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "returnDataHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "gasUsed",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "feeCharged",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receiverBefore",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "receiverAfter",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "hashQuestion",
    "inputs": [
      {
        "name": "q",
        "type": "tuple",
        "internalType": "struct Sworn.Question",
        "components": [
          {
            "name": "chainId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "blockNumber",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "blockHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "from",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "feeToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "gasLimit",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "release",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "reservationKey",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "reservations",
    "inputs": [
      {
        "name": "key",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "client",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "status",
        "type": "uint8",
        "internalType": "enum Sworn.Status"
      },
      {
        "name": "coverage",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "reserve",
    "inputs": [
      {
        "name": "q",
        "type": "tuple",
        "internalType": "struct Sworn.Question",
        "components": [
          {
            "name": "chainId",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "blockNumber",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "blockHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "from",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "data",
            "type": "bytes",
            "internalType": "bytes"
          },
          {
            "name": "feeToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "gasLimit",
            "type": "uint64",
            "internalType": "uint64"
          }
        ]
      },
      {
        "name": "a",
        "type": "tuple",
        "internalType": "struct Sworn.Answer",
        "components": [
          {
            "name": "success",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "returnDataHash",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "gasUsed",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "feeCharged",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "receiver",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "receiverBefore",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "receiverAfter",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "client",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "coverage",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "digest",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "servers",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "free",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "locked",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "unbondStart",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdraw",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "Bonded",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "funder",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Released",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "coverage",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Reserved",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "client",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "coverage",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "blockNumber",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "blockHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "expiry",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Slashed",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "digest",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "client",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "coverage",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "UnbondBegun",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "withdrawableAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Withdrawn",
    "inputs": [
      {
        "name": "server",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyUnbonding",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AmountTooLarge",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AnswerCorrect",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadCalldata",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BlockHashMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BlockOutOfWindow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DigestUsed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Expired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientFree",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoBond",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoReservation",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotTip20Token",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotUnbonding",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NothingToWithdraw",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PublicBlockHashMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "QuestionMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReceiverIsSender",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TokenTransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UnbondDelayNotOver",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unbonding",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VirtualReceiver",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongChain",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongGuestVersion",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroClient",
    "inputs": []
  }
] as const;
