//! Extracts the Moderato genesis `config` (hardfork activation times, chain id, epoch length) from
//! the vendored `tempo-chainspec` genesis file, so the guest uses Tempo's own schedule without
//! parsing the 2.5 MB genesis (alloc) at proving time. Every numeric `config` key is emitted.
use std::{env, fs, path::PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let genesis = manifest.join("../tempo/crates/chainspec/src/genesis/moderato.json");
    println!("cargo:rerun-if-changed={}", genesis.display());
    let v: serde_json::Value = serde_json::from_slice(&fs::read(&genesis).expect("read moderato.json")).unwrap();
    let cfg = v["config"].as_object().expect("config");
    let mut out = String::from("/// Generated by core/build.rs from tempo/crates/chainspec/src/genesis/moderato.json `config`.\npub const MODERATO_GENESIS_CONFIG: &[(&str, u64)] = &[\n");
    for (k, val) in cfg {
        if let Some(n) = val.as_u64() {
            out.push_str(&format!("    ({k:?}, {n}),\n"));
        }
    }
    out.push_str("];\n");
    fs::write(PathBuf::from(env::var("OUT_DIR").unwrap()).join("moderato_config.rs"), out).unwrap();
}
